2024-01-16 19:14:09,978 INFO    StreamThr :5780 [internal.py:wandb_internal():86] W&B internal server running at pid: 5780, started at: 2024-01-16 19:14:09.978436
2024-01-16 19:14:09,980 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status
2024-01-16 19:14:09,982 INFO    WriterThread:5780 [datastore.py:open_for_write():87] open: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\run-ctr6y1p7.wandb
2024-01-16 19:14:09,982 DEBUG   SenderThread:5780 [sender.py:send():382] send: header
2024-01-16 19:14:09,989 DEBUG   SenderThread:5780 [sender.py:send():382] send: run
2024-01-16 19:14:10,510 INFO    SenderThread:5780 [dir_watcher.py:__init__():211] watching files in: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\files
2024-01-16 19:14:10,510 INFO    SenderThread:5780 [sender.py:_start_run_threads():1136] run started: ctr6y1p7 with start time 1705428849.065849
2024-01-16 19:14:10,520 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: check_version
2024-01-16 19:14:10,520 DEBUG   SenderThread:5780 [sender.py:send_request():409] send_request: check_version
2024-01-16 19:14:10,682 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: run_start
2024-01-16 19:14:10,692 DEBUG   HandlerThread:5780 [system_info.py:__init__():27] System info init
2024-01-16 19:14:10,692 DEBUG   HandlerThread:5780 [system_info.py:__init__():42] System info init done
2024-01-16 19:14:10,692 INFO    HandlerThread:5780 [system_monitor.py:start():194] Starting system monitor
2024-01-16 19:14:10,692 INFO    SystemMonitor:5780 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-16 19:14:10,692 INFO    HandlerThread:5780 [system_monitor.py:probe():214] Collecting system info
2024-01-16 19:14:10,702 INFO    SystemMonitor:5780 [interfaces.py:start():190] Started cpu monitoring
2024-01-16 19:14:10,702 INFO    SystemMonitor:5780 [interfaces.py:start():190] Started disk monitoring
2024-01-16 19:14:10,702 INFO    SystemMonitor:5780 [interfaces.py:start():190] Started gpu monitoring
2024-01-16 19:14:10,702 INFO    SystemMonitor:5780 [interfaces.py:start():190] Started memory monitoring
2024-01-16 19:14:10,710 INFO    SystemMonitor:5780 [interfaces.py:start():190] Started network monitoring
2024-01-16 19:14:11,209 DEBUG   HandlerThread:5780 [system_info.py:probe():151] Probing system
2024-01-16 19:14:11,210 DEBUG   HandlerThread:5780 [system_info.py:_probe_git():136] Probing git
2024-01-16 19:14:11,210 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:11,210 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:11,282 DEBUG   HandlerThread:5780 [system_info.py:_probe_git():144] Probing git done
2024-01-16 19:14:11,282 DEBUG   HandlerThread:5780 [system_info.py:probe():199] Probing system done
2024-01-16 19:14:11,282 DEBUG   HandlerThread:5780 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.9.16', 'heartbeatAt': '2024-01-16T18:14:11.209228', 'startedAt': '2024-01-16T18:14:01.967254', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/BredaUniversityADSAI/2023-24b-fai2-adsai-DominikSzewczyk224180.git', 'commit': 'd9bc2408628fdfc9c02056258b83606e34f908e5'}, 'email': '112881814+DominikSzewczyk224180@users.noreply.github.com', 'root': 'C:/Users/domin/Desktop/Year 2 Block B/2023-24b-fai2-adsai-DominikSzewczyk224180', 'host': 'MSI', 'username': 'domin', 'executable': 'c:\\Users\\domin\\anaconda3\\envs\\tf\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2304.0, 'min': 0.0, 'max': 2304.0}, 'cpu_freq_per_core': [{'current': 2304.0, 'min': 0.0, 'max': 2304.0}], 'disk': {'/': {'total': 934.0361289978027, 'used': 606.9130401611328}}, 'gpu': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 Ti Laptop GPU', 'memory_total': 4294967296}], 'memory': {'total': 15.708477020263672}}
2024-01-16 19:14:11,282 INFO    HandlerThread:5780 [system_monitor.py:probe():224] Finished collecting system info
2024-01-16 19:14:11,282 INFO    HandlerThread:5780 [system_monitor.py:probe():227] Publishing system info
2024-01-16 19:14:11,282 DEBUG   HandlerThread:5780 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-01-16 19:14:11,282 ERROR   HandlerThread:5780 [system_info.py:_save_conda():219] Error saving conda packages: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\Users\domin\anaconda3\envs\tf\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 215, in _save_conda
    subprocess.call(
  File "c:\Users\domin\anaconda3\envs\tf\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\Users\domin\anaconda3\envs\tf\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\domin\anaconda3\envs\tf\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-01-16 19:14:11,282 DEBUG   HandlerThread:5780 [system_info.py:_save_conda():220] Saving conda packages done
2024-01-16 19:14:11,282 INFO    HandlerThread:5780 [system_monitor.py:probe():229] Finished publishing system info
2024-01-16 19:14:11,282 DEBUG   SenderThread:5780 [sender.py:send():382] send: files
2024-01-16 19:14:11,282 INFO    SenderThread:5780 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-01-16 19:14:11,293 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: python_packages
2024-01-16 19:14:11,293 DEBUG   SenderThread:5780 [sender.py:send_request():409] send_request: python_packages
2024-01-16 19:14:11,293 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: stop_status
2024-01-16 19:14:11,293 DEBUG   SenderThread:5780 [sender.py:send_request():409] send_request: stop_status
2024-01-16 19:14:11,293 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-16 19:14:11,303 INFO    HandlerThread:5780 [handler.py:handle_tbrecord():767] handling tbrecord: tbrecord {
  log_dir: "runs/ctr6y1p7\\runs/ctr6y1p7_1"
  save: true
}
control {
  relay_id: "9d3a5cf1bc6c4189858c164f1a81cdb1"
}
_info {
  stream_id: "ctr6y1p7"
}

2024-01-16 19:14:11,303 DEBUG   HandlerThread:5780 [config_util.py:dict_from_config_file():101] no default config file found in config-defaults.yaml
2024-01-16 19:14:11,514 INFO    Thread-31 :5780 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\files\conda-environment.yaml
2024-01-16 19:14:11,514 INFO    Thread-31 :5780 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\files\wandb-metadata.json
2024-01-16 19:14:11,514 INFO    Thread-31 :5780 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\files\requirements.txt
2024-01-16 19:14:11,584 DEBUG   SenderThread:5780 [sender.py:send():382] send: telemetry
2024-01-16 19:14:11,586 DEBUG   SenderThread:5780 [sender.py:send():382] send: telemetry
2024-01-16 19:14:11,805 DEBUG   SenderThread:5780 [sender.py:send():382] send: tbrecord
2024-01-16 19:14:11,805 DEBUG   SenderThread:5780 [sender.py:send():382] send: config
2024-01-16 19:14:11,805 DEBUG   SenderThread:5780 [sender.py:send():382] send: telemetry
2024-01-16 19:14:11,836 INFO    wandb-upload_0:5780 [upload_job.py:push():131] Uploaded file C:\Users\domin\AppData\Local\Temp\tmp3eo9wovewandb\rwt5av61-wandb-metadata.json
2024-01-16 19:14:12,519 INFO    Thread-31 :5780 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\files\output.log
2024-01-16 19:14:13,738 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:13,738 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:13,997 DEBUG   Thread-37 :5780 [tb_watcher.py:_process_events():284] Encountered tensorboard directory watcher error: [WinError 1314] A required privilege is not held by the client: 'c:\\Users\\domin\\Desktop\\Year 2 Block B\\2023-24b-fai2-adsai-DominikSzewczyk224180\\3. Reinforcement Learning\\runs\\ctr6y1p7\\runs\\ctr6y1p7_1\\events.out.tfevents.1705428851.MSI.22408.0' -> 'c:\\Users\\domin\\Desktop\\Year 2 Block B\\2023-24b-fai2-adsai-DominikSzewczyk224180\\3. Reinforcement Learning\\wandb\\run-20240116_191401-ctr6y1p7\\files\\events.out.tfevents.1705428851.MSI.22408.0'
2024-01-16 19:14:14,530 INFO    Thread-31 :5780 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\files\output.log
2024-01-16 19:14:15,828 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:16,253 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:16,253 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:18,771 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:18,771 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:20,874 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:21,284 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:21,284 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:23,802 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:23,802 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:25,907 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:26,291 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: stop_status
2024-01-16 19:14:26,291 DEBUG   SenderThread:5780 [sender.py:send_request():409] send_request: stop_status
2024-01-16 19:14:26,306 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-16 19:14:26,312 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:26,312 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:28,851 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:28,851 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:31,352 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:31,352 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:31,795 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:33,855 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:33,856 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:36,365 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:36,367 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:36,840 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:38,881 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:38,882 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:41,310 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: stop_status
2024-01-16 19:14:41,310 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-16 19:14:41,311 DEBUG   SenderThread:5780 [sender.py:send_request():409] send_request: stop_status
2024-01-16 19:14:41,387 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:41,388 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:42,573 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:43,899 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:43,901 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:46,416 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:46,416 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:46,827 INFO    Thread-31 :5780 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\domin\Desktop\Year 2 Block B\2023-24b-fai2-adsai-DominikSzewczyk224180\3. Reinforcement Learning\wandb\run-20240116_191401-ctr6y1p7\files\config.yaml
2024-01-16 19:14:48,962 ERROR   gpu       :5780 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-01-16 19:14:48,970 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:48,970 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:51,480 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:51,480 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:51,535 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:54,032 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:54,032 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:56,308 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-16 19:14:56,308 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: stop_status
2024-01-16 19:14:56,308 DEBUG   SenderThread:5780 [sender.py:send_request():409] send_request: stop_status
2024-01-16 19:14:56,551 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:56,551 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:56,778 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:14:59,061 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:14:59,061 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:01,592 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:01,592 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:01,813 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:15:04,103 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:04,103 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:06,616 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:06,616 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:06,855 DEBUG   HandlerThread:5780 [handler.py:handle_request():146] handle_request: status_report
2024-01-16 19:15:09,142 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-01-16 19:15:09,143 ERROR   gpu       :5780 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
